=== lonelysarab/bplustrees/trunk/html_root/doc/php_inc/program_listing.dtd
<!-- Document type definition for program_listing xml document -->
<!ELEMENT program_listing (line+)>
<!ELEMENT line ((#PCDATA | replace)+)>
<!ATTLIST line line_number CDATA #IMPLIED>
<!ELEMENT replace EMPTY>
<!ATTLIST replace var NMTOKEN #REQUIRED>
<!ENTITY lt "&#60;">
<!ENTITY gt "&#62;">
<!ENTITY amp "&#38;">
<!ENTITY quot "&#34;">

=== lonelysarab/bplustrees/trunk/html_root/doc/program_listing/template.xml
<?xml version="1.0"?>
<!DOCTYPE program_listing SYSTEM "../php_inc/program_listing.dtd">
<program_listing>
	<line line_number="1">1 int greater(int x, int y)  // y = <replace var="y" />, x = <replace var="x" /></line>
	<line line_number="2">2 {</line>
	<line line_number="naps">3 	int z = <replace var="y" />;</line>
	<line line_number="naps">4 	z = <replace var="y" />;</line>
	<line line_number="4">4 This is an example program</line>
</program_listing>

=== lonelysarab/bplustrees/html_root/doc/program_listing/other.xml
<?xml version="1.0"?>
<!DOCTYPE program_listing SYSTEM "../php_inc/program_listing.dtd">
<program_listing>
	<line line_number="1">1 int greatestCommonDivisor(int x, int y)</line>
	<line line_number="2">2 {</line>
	<line line_number="3">3 	if(<replace var="y" /> &lt; <replace var="x" />)</line>
	<line line_number="4">4 	...</line>
	<line line_number="5">5 	return gcd;</line>
	<line line_number="6">6 }</line>
</program_listing>
