=== lonelysarab/bplustrees/trunk/client/src/jhave/client/visualizers.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : visualizers.xsd
    Created on : June 16, 2005, 5:08 PM
    Author     : gaffneyc
    Description:
        Purpose of XML Schema document follows.
-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:ns="http://csf11.acs.uwosh.edu/jhave">

    <xsd:element name="visualizers" type="VisualizerList"/>
    
    <xsd:complexType name="VisualizerList">
        <xsd:sequence>
            <xsd:element name="visualizer" type="VisualizerType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="VisualizerType">
        <xsd:sequence>
            <xsd:element name="class" type="SimpleValue" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="extension" type="SimpleValue" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="SimpleValue">
        <xsd:attribute name="value" type="xsd:string" use="required"/>
    </xsd:complexType>
</xsd:schema>

=== lonelysarab/bplustrees/client/src/jhave/client/visualizers.xml
<?xml version="1.0" encoding="utf-8"?>
<visualizers xsi:noNamespaceSchemaLocation="visualizers.xsd"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <visualizer name="Gaigs">
        <class value="gaigs2.GaigsAV"/>
        <extension value="sho"/>
        <extension value="gaigs"/>
    </visualizer>
    <visualizer name="Gaff">
        <class value="org.gaffneyc.gaff.GaffVisualizer"/>
        <extension value="gaff"/>
    </visualizer>
    <visualizer name="Animal">
       <class value="animal.main.AnimalVisualizer"/>
       <extension value="aml"/>
   </visualizer>
   <visualizer name="AnimalScript">
       <class value="animal.main.AnimalScriptVisualizer"/>
       <extension value="asu"/>
   </visualizer>
    <visualizer name="xaal">
        <class value="xaal.adapters.jhave.XaalAV"/>
        <extension value="xaal"/>
    </visualizer>
    <visualizer name="Matrix">
    	<class value="jhavematrix.MatrixVisualizer"/>
    	<extension value="matrix"/>
    </visualizer>
</visualizers>
